name: Check code/commit conventions

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Rerun Pre-Commit Hooks on CI
        run: |
          pip install -r requirements.txt
          pre-commit run --color=always --show-diff-on-failure --all-files
  commitlint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
